Refactor Server&group rule
YuanYuanOwO/Minecraft-Tianji-Server pull request #20
Opened 2022-04-15 06:48 UTC by YuanYuanOwO

For v2
need to review

2022-04-19 13:21 UTC, YuanYuanOwO commented
need some suggestions :)
you can write here

2022-04-19 19:37 UTC, RMSCA requested changes
语意重复，建议把交流群规则的两个板块合并

2022-04-20 09:56 UTC, YuanYuanOwO commented
> 

Got it

2022-04-20 17:48 UTC, RMSCA requested changes
加两条：
1. 请遵守腾讯qq的软件许可及服务协议
2. 天际服管理组对以上条款拥有最终裁定权和解释权

第一条建议加开头，第二条建议加结尾

2022-04-21 10:00 UTC, YuanYuanOwO commented
> 加两条：
> 
> 1. 请遵守腾讯qq的软件许可及服务协议
> 2. 天际服管理组对以上条款拥有最终裁定权和解释权
> 
> 第一条建议加开头，第二条建议加结尾

第二条已经有了来着..

2022-04-21 10:12 UTC, YuanYuanOwO commented on server-rule.md
>  - 进行作弊、恶意卡服等行为;
这里感觉要改一下比较好，但是不太清楚要怎么改

2022-04-21 18:13 UTC, RMSCA commented on server-rule.md
>  - 进行作弊、恶意卡服等行为;
直接改成无效证据呗
前面哔哩吧啦说了一大堆不还是无效证据的意思嘛

2022-04-23 12:40 UTC, merged